/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import konversibilangan.KonversiBilangan;

/**
 *
 * @author AINAN-Gaul
 */
public class Heksadesimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Heksadesimal
     */
    public Heksadesimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputHexa = new javax.swing.JTextField();
        HexaBiner = new javax.swing.JButton();
        HexaDesimal = new javax.swing.JButton();
        HexaOktal = new javax.swing.JButton();
        outputHexa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Konversi Bilangan Heksadesimal");
        setToolTipText("");
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(250, 150));
        setPreferredSize(new java.awt.Dimension(400, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHexaActionPerformed(evt);
            }
        });
        getContentPane().add(inputHexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, 30));

        HexaBiner.setText("Biner");
        HexaBiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexaBinerActionPerformed(evt);
            }
        });
        getContentPane().add(HexaBiner, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, -1));

        HexaDesimal.setText("Desimal");
        HexaDesimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexaDesimalActionPerformed(evt);
            }
        });
        getContentPane().add(HexaDesimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));

        HexaOktal.setText("Oktal");
        HexaOktal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexaOktalActionPerformed(evt);
            }
        });
        getContentPane().add(HexaOktal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, -1));

        outputHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputHexaActionPerformed(evt);
            }
        });
        getContentPane().add(outputHexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 120, 30));

        jLabel1.setText("Masukkan bilangan biner:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Hasil:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHexaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHexaActionPerformed

    private void HexaBinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexaBinerActionPerformed
        // TODO add your handling code here:
        KonversiBilangan kb = new KonversiBilangan();
        String input = inputHexa.getText();
        String hasil = kb.HexatoBiner(input);
        outputHexa.setText(hasil);
    }//GEN-LAST:event_HexaBinerActionPerformed

    private void HexaDesimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexaDesimalActionPerformed
        // TODO add your handling code here:
        KonversiBilangan kb = new KonversiBilangan();
        String input = inputHexa.getText();
        int hasil = kb.HexatoDesimal(input);
        outputHexa.setText(Integer.toString(hasil));
    }//GEN-LAST:event_HexaDesimalActionPerformed

    private void HexaOktalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexaOktalActionPerformed
        // TODO add your handling code here:
        KonversiBilangan kb = new KonversiBilangan();
        String input = inputHexa.getText();
        String hasil = kb.HexatoOktal(input);
        outputHexa.setText(hasil);
    }//GEN-LAST:event_HexaOktalActionPerformed

    private void outputHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputHexaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputHexaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HexaBiner;
    private javax.swing.JButton HexaDesimal;
    private javax.swing.JButton HexaOktal;
    private javax.swing.JTextField inputHexa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField outputHexa;
    // End of variables declaration//GEN-END:variables
}
